version: '3'

services:
  db:
    image: postgres
    restart: always
    shm_size: '2gb'
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - database-variables.env
